spring:
  application:
    name: bookShopDemo
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  sql:
    init:
      mode:
      platform: h2
      schema-locations:
        - classpath:schema.sql
      data-locations:
        - classpath:data.sql

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    com.example.bookShopDemo: DEBUG